
CREATE TABLE IF NOT EXISTS student (
id INT NOT NULL AUTO_INCREMENT,
jmbag VARCHAR(10) UNIQUE NOT NULL,
first_name VARCHAR(255) NOT NULL,
last_name VARCHAR(255) NOT NULL,
date_of_birth DATE NOT NULL,
number_of_ects INT NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS course (
id INT NOT NULL AUTO_INCREMENT,
name VARCHAR(255) NOT NULL,
number_of_ects INT NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS student_course(
course_id INT NOT NULL,
student_id INT NOT NULL,
CONSTRAINT FK_student
        FOREIGN KEY (student_id) REFERENCES student(id) ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT FK_course
        FOREIGN KEY (course_id) REFERENCES course(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS user(
id INT NOT NULL AUTO_INCREMENT,
username VARCHAR(255) NOT NULL,
password VARCHAR(255) NOT NULL,
firstname VARCHAR(25) NOT NULL,
lastname VARCHAR(255) NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS authority(
id INT NOT NULL AUTO_INCREMENT,
name VARCHAR(255) NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS user_authority(
user_id INT NOT NULL,
authority_id INT NOT NULL,
FOREIGN KEY (user_id) REFERENCES user(id),
FOREIGN KEY (authority_id) REFERENCES authority(id)
);